name: ntfluttery
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  http_mock_adapter: ^0.6.1
  lints: ^2.1.0
  mockito: ^5.4.4
  test: ^1.24.0
